/* ==========================================================================
   Dominica Sol — build
   --------------------------------------------------------------------------
   Assembles the public site into dist/:
     1. copies the pages, css, js, assets and the admin
     2. turns content/*.json (edited through /admin) into dist/js/data.js
     3. makes an 800px thumbnail (<name>-t.<ext>) for every photo, and
        shrinks any photo wider/taller than MAX_EDGE so a 20 MB upload
        never reaches a visitor.
   Steps 3 needs `sharp` (npm install). Without it the build still works;
   the grids simply fall back to the full-size photos.
   ========================================================================== */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const COPY = ['index.html', 'shop.html', 'work.html', 'piece.html', 'projects.html', '404.html',
              'css', 'js', 'assets', 'admin'];
const THUMB_EDGE = 800;
const MAX_EDGE = 2000;      // anything larger is resized down to FULL_EDGE
const FULL_EDGE = 1600;
const IMAGE_RE = /\.(jpe?g|png|webp)$/i;
const THUMB_RE = /-t\.(jpe?g|png|webp)$/i;

let sharp = null;
try { sharp = require('sharp'); } catch (e) {
  console.warn('! sharp is not installed — skipping thumbnails (run `npm install`).');
}

function readJSON(file) { return JSON.parse(fs.readFileSync(file, 'utf8')); }

function readFolder(dir) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) return [];
  return fs.readdirSync(full)
    .filter(f => f.endsWith('.json'))
    .map(f => Object.assign({ slug: f.replace(/\.json$/, '') }, readJSON(path.join(full, f))));
}

// Entries without a position come first (newest additions on top), then by position.
function byOrder(a, b) {
  const ao = typeof a.order === 'number' ? a.order : -Infinity;
  const bo = typeof b.order === 'number' ? b.order : -Infinity;
  return ao - bo || a.title.localeCompare(b.title);
}

function cleanImages(entry) {
  let imgs = entry.images || [];
  if (typeof imgs === 'string') imgs = [imgs];
  entry.images = imgs.filter(Boolean).map(s => '/' + String(s).replace(/^\/+/, ''));
  return entry;
}

function walk(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    if (fs.statSync(p).isDirectory()) walk(p, out); else out.push(p);
  }
  return out;
}

// Plain content copy (no permissions carried over — some file systems object).
function copy(src, dest) {
  if (fs.statSync(src).isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const name of fs.readdirSync(src)) {
      if (name === '.DS_Store') continue;
      copy(path.join(src, name), path.join(dest, name));
    }
  } else {
    fs.writeFileSync(dest, fs.readFileSync(src));
  }
}

async function processImages() {
  if (!sharp) return;
  const files = walk(path.join(DIST, 'assets'), []).filter(f => IMAGE_RE.test(f) && !THUMB_RE.test(f));
  let thumbs = 0, shrunk = 0;
  for (const file of files) {
    const meta = await sharp(file).metadata();
    if (Math.max(meta.width || 0, meta.height || 0) > MAX_EDGE) {
      const buf = await sharp(file).rotate()
        .resize(FULL_EDGE, FULL_EDGE, { fit: 'inside', withoutEnlargement: true })
        .toBuffer();
      fs.writeFileSync(file, buf);
      shrunk++;
    }
    const thumb = file.replace(IMAGE_RE, m => '-t' + m);
    if (!fs.existsSync(thumb)) {
      await sharp(file).rotate()
        .resize(THUMB_EDGE, THUMB_EDGE, { fit: 'inside', withoutEnlargement: true })
        .toFile(thumb);
      thumbs++;
    }
  }
  console.log(`  photos: ${files.length} · thumbnails made: ${thumbs} · oversized shrunk: ${shrunk}`);
}

async function main() {
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });
  for (const item of COPY) {
    const src = path.join(ROOT, item);
    if (fs.existsSync(src)) copy(src, path.join(DIST, item));
  }

  const visible = e => e.published !== false;
  const items = readFolder('content/pieces').filter(visible).map(cleanImages)
    .filter(e => e.images.length).sort(byOrder);
  const projects = readFolder('content/projects').filter(visible).map(cleanImages).sort(byOrder);
  const site = readJSON(path.join(ROOT, 'content/site/settings.json'));
  const home = readJSON(path.join(ROOT, 'content/site/home.json'));

  // Filter buttons: fixed order, only the categories that actually have pieces.
  const known = ['Claws', 'Teeth', 'Earrings'];
  const present = Array.from(new Set(items.map(i => i.category)));
  const categories = ['All'].concat(known.filter(c => present.includes(c)),
                                    present.filter(c => !known.includes(c)));

  const js = '/* GENERATED by scripts/build.js from content/ — do not edit by hand. */\n' +
    'var SITE = ' + JSON.stringify(site, null, 2) + ';\n' +
    'var HOME = ' + JSON.stringify(home, null, 2) + ';\n' +
    'var SHOP_CATEGORIES = ' + JSON.stringify(categories) + ';\n' +
    'var ITEMS = ' + JSON.stringify(items, null, 2) + ';\n' +
    'var PROJECTS = ' + JSON.stringify(projects, null, 2) + ';\n';
  fs.writeFileSync(path.join(DIST, 'js', 'data.js'), js);
  console.log(`  pieces: ${items.length} · projects: ${projects.length} · projects page public: ${!!site.show_projects}`);

  await processImages();
  console.log('Built dist/');
}

main().catch(err => { console.error(err); process.exit(1); });
